### PR TITLE
fix deprecated font import path

### PR DESCRIPTION
**Pull request by emindemirhan**
Hello Onur, the path where the font is imported has become deprecated, causing a delay of 4.5 seconds in the mobile view of the website due to LCP. If you compare the PageSpeed Insight of my site with yours, you will see the difference. 

emndmrhn.dev:  https://pagespeed.web.dev/analysis/https-emndmrhn-dev/uwftynbwat?form_factor=mobile
onur.dev: https://pagespeed.web.dev/analysis/https-onur-dev/9evajo1fl2?form_factor=mobile

### CODE REVIEW

**Review by suyalcinkaya — COMMENTED** [review]
Awesome find, thank you! I think the build is failing because of the outdated version. Could you also upgrade the `geist` package with `bun`?

```bash
bun add geist
```

**Comment by emindemirhan** [comment]
> Awesome find, thank you! I think the build is failing because of the outdated version. Could you also upgrade the `geist` package with `bun`?
> 
> ```shell
> bun add geist
> ```

You're welcome. It was my pleasure. I updated the Geist version in the package.json with Bun. I think it's ready to build now.

**Comment by suyalcinkaya** [comment]
Still fails somehow 👀

image

**Comment by emindemirhan** [comment]
> Still fails somehow 👀
> 
> image

It's actually confusing why it's looking for that font in '/font/sans' path instead of 'geist/font/sans', which is where it should be looking for that module. When I build locally, it works fine without any issues, even without updating the 'geist' package. Since this is my first pull request, I'm not sure if I'm doing something wrong. Should I merge it into the master branch?  I can't fully comprehend why, but it seems to vercel taking the path incorrectly in building time.

**Comment by suyalcinkaya** [comment]
It worked here: https://github.com/suyalcinkaya/onur.dev/pull/59. Maybe there were mismatching versions between `next` and `geist`, not sure tbh. Thank you for letting me know tho, much appreciated! 🙌

**Comment by emindemirhan** [comment]
> It worked here: https://github.com/suyalcinkaya/onur.dev/pull/59. Maybe there were mismatching versions between `next` and `geist`, not sure tbh. Thank you for letting me know tho, much appreciated! 🙌

Your welcome, and also thank to you for this beautiful website i really appreciated.

**Pull request closed without merging**
